services:

  # Database
  leafylane-mysql-db:
    image: mysql:8
    container_name: leafylane-mysql-db
    hostname: leafylane-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'leafylane_db'
      MYSQL_USER: 'leafylaneDBA'
      MYSQL_PASSWORD: 'PaSSworD'
      MYSQL_ROOT_PASSWORD: 'r00tPaSSworD'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - leafylane-db-volume:/var/lib/mysql
    networks:
      - leafylane-app-network

  # Core services
  leafylane-consul-discovery:
    hostname: leafylane-consul-discovery
    image: hashicorp/consul
    container_name: leafylane-consul-discovery
    restart: always
    ports:
      - "8500:8500"
    networks:
      - leafylane-app-network

  leafylane-spring-cloud-api-gateway-server:
    build:
      context: ./leafylane-api-gateway-service
      args:
        JAR_FILE: leafylane-api-gateway-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: leafylane-spring-cloud-api-gateway-server
    container_name: leafylane-spring-cloud-api-gateway-server
    hostname: leafylane-spring-cloud-api-gateway-server
    ports:
      - "8765:8765"
    networks:
      - leafylane-app-network
    environment:
      - SERVER_PORT=8765
      - ZIPKIN_HOST=leafylane-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker

  leafylane-auth-server:
    build:
      context: ./leafylane-oauth2-authorization-server
      args:
        JAR_FILE: leafylane-oauth2-authorization-server-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: leafylane-auth-server
    container_name: leafylane-auth-server
    hostname: leafylane-auth-server
    ports:
      - "9080:9080"
    networks:
      - leafylane-app-network
    environment:
      - SERVER_PORT=9080
      - ZIPKIN_HOST=leafylane-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker


  leafylane-account-service:
    build:
      context: ./leafylane-account-service
      args:
        JAR_FILE: leafylane-account-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: leafylane-account-service
    container_name: leafylane-account-service
    hostname: leafylane-account-service
    ports:
      - "4001:4001"
    networks:
      - leafylane-app-network
    environment:
      - SERVER_PORT=4001
      - ZIPKIN_HOST=leafylane-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker

  leafylane-billing-service:
    build:
      context: ./leafylane-address-service
      args:
        JAR_FILE: leafylane-address-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: leafylane-address-service
    container_name: leafylane-address-service
    hostname: leafylane-address-service
    ports:
      - "5001:5001"
    networks:
      - leafylane-app-network
    environment:
      - SERVER_PORT=5001
      - ZIPKIN_HOST=leafylane-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker

  leafylane-catalog-service:
    build:
      context: ./leafylane-catalogue-service
      args:
        JAR_FILE: leafylane-catalogue-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: leafylane-catalogue-service
    container_name: leafylane-catalogue-service
    hostname: leafylane-catalogue-service
    ports:
      - "6001:6001"
    networks:
      - leafylane-app-network
    environment:
      - SERVER_PORT=6001
      - ZIPKIN_HOST=leafylane-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker

  leafylane-order-service:
    build:
      context: ./leafylane-order-service
      args:
        JAR_FILE: leafylane-order-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: leafylane-order-service
    container_name: leafylane-order-service
    hostname: leafylane-order-service
    ports:
      - "7001:7001"
    networks:
      - leafylane-app-network
    environment:
      - SERVER_PORT=7001
      - ZIPKIN_HOST=leafylane-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker

  leafylane-payment-service:
    build:
      context: ./leafylane-payment-service
      args:
        JAR_FILE: leafylane-payment-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: leafylane-payment-service
    container_name: leafylane-payment-service
    hostname: leafylane-payment-service
    ports:
      - "8001:8001"
    networks:
      - leafylane-app-network
    environment:
      - SERVER_PORT=8001
      - ZIPKIN_HOST=leafylane-zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker

  leafylane-notification-service:
    build:
      context: ./leafylane-notification-service
      dockerfile: Dockerfile
    image: leafylane-notification-service
    container_name: leafylane-notification-service
    hostname: leafylane-notification-service
    depends_on:
      - leafylane-rabbitmq
    networks:
      - leafylane-app-network
    environment:
      - EMAIL_SENDER=youremail@gmail.com
      - EMAIL_PASSWORD=
      - EMAIL_RECIPIENT=otheremail@gmail.com
      - RABBITMQ_URL=amqp://user:pass@leafylane-rabbitmq/
    ports:
      - "9001:9001"
  # Monitoring Services
  leafylane-prometheus:
    build:
      context: ./leafylane-prometheus
      dockerfile: Dockerfile
    image: leafylane-prometheus
    container_name: leafylane-prometheus
    hostname: leafylane-prometheus
    ports:
      - "9090:9090"
    networks:
      - leafylane-app-network

  leafylane-grafana:
    build:
      context: ./leafylane-graphana
      dockerfile: Dockerfile
    image: leafylane-graphana
    container_name: leafylane-graphana
    hostname: leafylane-graphana
    ports:
      - "3030:3000"
    volumes:
      - leafylane-graphana-volume:/var/lib/grafana
    networks:
      - leafylane-app-network

  leafylane-rabbitmq:
    image: rabbitmq:3-management
    container_name: leafylane-rabbitmq
    hostname: leafylane-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      - leafylane-app-network

#  # Monitoring using TICK stack.
#  leafylane-telegraf:
#    build:
#      context: ./leafylane-telegraph
#      dockerfile: Dockerfile
#    image: leafylane-telegraf
#    container_name: leafylane-telegraf
#    hostname: leafylane-telegraf
#    environment:
#      HOSTNAME: "leafylane-telegraf"
#    ports:
#      - "8125:8125/udp"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - leafylane-app-network
#
#  leafylane-influxdb:
#    image: influxdb:1.8
#    container_name: leafylane-influxdb
#    hostname: leafylane-influxdb
#    volumes:
#      - leafylane-influxdb-volume:/var/lib/influxdb
#    ports:
#      - "8086:8086"
#    networks:
#      - leafylane-app-network
#
#  leafylane-chronograf:
#    image: chronograf:1.7.3
#    container_name: leafylane-chronograf
#    hostname: leafylane-chronograf
#    environment:
#      INFLUXDB_URL: http://leafylane-influxdb:8086
#      KAPACITOR_URL: http://leafylane-kapacitor:9092
#    volumes:
#      - leafylane-chronograf-volume:/var/lib/chronograf
#    ports:
#      - "8888:8888"
#    restart: always
#    networks:
#      - leafylane-app-network
#
#  leafylane-kapacitor:
#    image: kapacitor
#    container_name: leafylane-kapacitor
#    hostname: leafylane-kapacitor
#    environment:
#      KAPACITOR_HOSTNAME: leafylane-kapacitor
#      KAPACITOR_INFLUXDB_0_URLS_0: http://leafylane-influxdb:8086
#    ports:
#      - "9092:9092"
#    networks:
#      - leafylane-app-network

volumes:
  leafylane-db-volume:
  leafylane-graphana-volume:
#  leafylane-telegraph-volume:
#  leafylane-influxdb-volume:
#  leafylane-chronograf-volume:

networks:
  leafylane-app-network:
    driver: bridge
