MYSQL_USERNAME: "root"
MYSQL_PASSWORD: "root"
MYSQL_URL: "jdbc:mysql://localhost:3306/integrated_oauth?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
server:
  port: ${SERVER_PORT:9080}
spring:
  application:
    name: auth-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root} # update username
    password: ${MYSQL_PASSWORD:root} # update password
    url: ${MYSQL_URL}

  flyway:
    baseline-on-migrate: true
    baseline-description: <<Flyway Baseline>>
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    fail-on-missing-locations: true


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

---

spring:
  config:
    activate:
      on-profile: local
  cloud:
    bus:
      enabled: false
    consul:
      enabled: false #consul discovery set false, in this profile eureka discovery is enabled.
  jpa:
    database: h2
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:

      show_sql: true
      use_sql_comments: true
      format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:leafylane_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE;SCHEMA=PUBLIC;
    username: sa
    password:
  h2:
    console:
      enabled: true
management:
  influx:
    metrics:
      export:
        enabled: false
---

spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leafylane_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
---

spring:
  config:
    activate:
      on-profile: docker
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://leafylane-mysql-db:3306/leafylane_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: leafylaneDBA
    password: PaSSworD
  cloud:
    consul:
      host: leafylane-consul-discovery
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
      enabled: true #consul discovery is enabled in this profile

management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      statsd:
        enabled: true
        flavor: telegraf
        port: 8125
      influx: #pushing influx metrics.
        db: leafylane_influxdb_monitoring_metrics
        uri: http://leafylane-influxdb:8086
        auto-create-db: true
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    enabled: false #eureka discovery set false, in this profile consul discovery is enabled.