apiVersion: v1
kind: Service
metadata:
  namespace: leafylane
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: leafylane-prometheus
  name: leafylane-prometheus
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: leafylane-prometheus
