apiVersion: v1
kind: Service
metadata:
  namespace: leafylane
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: leafylane-grafana
  name: leafylane-grafana
spec:
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3000
      nodePort: 30300   # Port on which the service will be available externally
  type: NodePort
  selector:
    io.kompose.service: leafylane-grafana
