apiVersion: v1
kind: Service
metadata:
  namespace: leafylane
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: leafylane-consul-discovery
  name: leafylane-consul-discovery
spec:
  ports:
    - name: "8500"
      port: 8500
      targetPort: 8500
  selector:
    io.kompose.service: leafylane-consul-discovery
