apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: leafylane
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: leafylane-auth-server
  name: leafylane-auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: leafylane-auth-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: leafylane-auth-server
    spec:
      containers:
        - env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: ZIPKIN_HOST
              value: leafylane-zipkin:9411
          image: sushilasubedi/leafylane-auth-server
          name: leafylane-auth-server
          ports:
            - containerPort: 8080
              protocol: TCP
      hostname: leafylane-auth-server
      restartPolicy: Always
