apiVersion: v1
kind: Service
metadata:
  namespace: leafylane
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: leafylane-account-service
  name: leafylane-account-service
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
  selector:
    io.kompose.service: leafylane-account-service
