apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: leafylane
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: leafylane-account-service
  name: leafylane-account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: leafylane-account-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: leafylane-account-service
    spec:
      containers:
        - env:
            - name: SERVER_PORT
              value: "4001"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: ZIPKIN_HOST
              value: leafylane-zipkin:9411
          image: sushilasubedi/leafylane-account-service:latest
          name: leafylane-account-service
          ports:
            - containerPort: 4001
              protocol: TCP
      hostname: leafylane-account-service
      restartPolicy: Always
