server:
  port: 8765
#  servlet:
#    session:
#      cookie:
#        name: CLIENT-SESSION
spring:
  application:
    name: leafylane-api-gateway-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: leafylane-account-service
    message-timeout: 10
  cloud:
    gateway:
      routes:
        - id: leafylane-account-service
          uri: http://localhost:4001/
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=2
        - id: leafylane-catalogue-service
          uri: http://localhost:6001/
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2
        - id: leafylane-address-service
          uri: http://localhost:5001/
          predicates:
            - Path=/api/billing/**
          filters:
            - StripPrefix=2
        - id: leafylane-payment-service
          uri: http://localhost:8001/
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=2
        - id: leafylane-order-service
          uri: http://localhost:7001/
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
---

spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9080
          jwk-set-uri: http://127.0.0.1:9080/oauth2/jwks # Add jwkSetUri configuration, resource server will not ping authorization server on startup.
  #management:
  #  tracing:
  #    sampling:
  #      probability: 1.0
  #  metrics:
  #    export:
  #      statsd:
  #        enabled: true
  #        flavor: telegraf
  #        port: 8125
  #      influx: #pushing influx metrics.
  #        db: leafylane_influxdb_monitoring_metrics
  #        uri: http://leafylane-influxdb:8086
  #        auto-create-db: true
  #      prometheus:
  #        enabled: true
  #  endpoints:
  #    web:
  #      exposure:
  #        include: "*"

---

spring:
  config:
    activate:
      on-profile: local, mysql
  cloud:
    bus:
      enabled: false
    consul:
      enabled: false #consul discovery set false, in this profile eureka discovery is enabled.
management:
  influx:
    metrics:
      export:
        enabled: false
---

spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://leafylane-auth-server:9080
          jwk-set-uri: http://leafylane-auth-server:9080/oauth2/jwks # Add jwkSetUri configuration, resource server will not ping authorization server on startup.
  cloud:
    consul:
      host: leafylane-consul-discovery
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
      enabled: true #consul discovery is enabled in this profile
    gateway:
      routes:
        - id: leafylane-account-service
          uri: http://leafylane-account-service:4001/
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=2
        - id: leafylane-catalogue-service
          uri: http://leafylane-catalogue-service:6001/
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2
        - id: leafylane-address-service
          uri: http://leafylane-address-service:5001/
          predicates:
            - Path=/api/billing/**
          filters:
            - StripPrefix=2
        - id: leafylane-payment-service
          uri: http://leafylane-payment-service:8001/
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=2
        - id: leafylane-order-service
          uri: http://leafylane-order-service:7001/
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
        - id: leafylane-notification-service
          uri: http://leafylane-notification-service:8083
          predicates:
            - Path=/api/notification/**
          filters:
            - StripPrefix=2
management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      statsd:
        enabled: true
        flavor: telegraf
        port: 8125
      influx: #pushing influx metrics.
        db: leafylane_influxdb_monitoring_metrics
        uri: http://leafylane-influxdb:8086
        auto-create-db: true
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    enabled: false #eureka discovery set false, in this profile consul discovery is enabled.