CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR(255) NOT NULL,
    AVAILABLE_ITEM_COUNT INTEGER NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(255),
    PRICE DOUBLE NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_CATEGORY_ID VARCHAR(255),
    PRODUCT_IMAGE_ID VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE PRODUCT_CATEGORY (
    PRODUCT_CATEGORY_ID VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRODUCT_CATEGORY_NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PRODUCT_CATEGORY_ID)
);

ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_PRODUCT_TO_PRODUCT_CATEGORY
    FOREIGN KEY (PRODUCT_CATEGORY_ID)
    REFERENCES PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID);

CREATE TABLE REVIEW (
    REVIEW_ID VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255),
    RATING_VALUE DOUBLE NOT NULL,
    REVIEW_MESSAGE VARCHAR(1000),
    PRODUCT_ID VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REVIEW_ID)
);
